[package]
name = "banners"
version = "1.0.0"
entrypoint = "lib.typ"
authors = ["TheZipCreator"]
license = "MIT"
description = "Allows you to write with Minecraft banners."
repository = "https://git.sr.ht/~thezipcreator/typst-banners/"
homepage = "https://sr.ht/~thezipcreator/typst-banners/"
categories = ["text"]
